import type { CSSObject } from '../../_util/cssinjs';
import { genComponentStyleHook } from '../../theme/internal';

export interface ComponentToken {}

// 修复源项目 bug：
// 1) 去掉第三参数 'xy-galleria'，让 genComponentStyleHook('Galleria') 自动推导 componentCls = '.xy-galleria'
// 2) 保留 keyframes 定义和全局过渡类
export default genComponentStyleHook('Galleria', token => {
  const {
    componentCls,
    colorBorder,
    borderRadius,
    colorTextSecondary,
    colorText,
    colorBgLayout,
    colorBorderSecondary,
    colorTextDisabled,
    colorPrimary,
    colorTextLightSolid,
  } = token;
  const maskBg = (token as any).colorBgMask || 'rgba(0,0,0,0.45)';
  const duration = '0.2s';
  const focusShadow = `0 0 0 2px color-mix(in srgb, ${colorPrimary} 20%, transparent)`;
  const navBtnBg = 'rgba(255,255,255,0.1)';
  const navBtnHoverBg = 'rgba(255,255,255,0.2)';
  const na = navBtnBg;
  const nh = navBtnHoverBg;
  return {
    '@keyframes xy-galleria-enter': { from: { opacity: 0, transform: 'scale(0.93)' } },
    '@keyframes xy-galleria-leave': {
      from: { opacity: 1, transform: 'scale(1)' },
      to: { opacity: 0, transform: 'scale(0.93)' },
    },
    [componentCls]: {
      overflow: 'hidden',
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: colorBorder,
      borderRadius: `${borderRadius}px`,
      '&-mask': {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: maskBg,
        opacity: 1,
        transition: 'opacity 0.2s ease-in-out',
        '&-leave-active': { opacity: 0 },
      },
      '&-content': { display: 'flex', flexDirection: 'column' },
      '&-items-container': { display: 'flex', flexDirection: 'column', position: 'relative' },
      '&-items': { position: 'relative', display: 'flex', height: '100%' },
      '&-nav-button': {
        position: 'absolute',
        top: '50%',
        display: 'inline-flex',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        background: na,
        color: colorTextSecondary,
        width: '3rem',
        height: '3rem',
        transition: `background ${duration},color ${duration},outline-color ${duration},box-shadow ${duration}`,
        margin: 'calc(-3rem / 2) 0.5rem 0 0.5rem',
        padding: 0,
        userSelect: 'none',
        border: '0 none',
        cursor: 'pointer',
        outlineColor: 'transparent',
        '&:not(&-disabled):hover': { background: nh, color: colorText },
        '&:not(&-disabled):focus-visible': {
          boxShadow: focusShadow,
          outline: '2px solid ' + colorPrimary,
          outlineOffset: '2px',
        },
        '&-disabled': { opacity: 0.6, pointerEvents: 'none' },
      },
      '&-prev-button': { borderRadius: '50%', left: 0 },
      '&-next-button': { borderRadius: '50%', right: 0 },
      '&-prev-button:dir(rtl), &-next-button:dir(rtl)': { transform: 'rotate(180deg)' },
      '&-prev-icon, &-next-icon': { fontSize: '1.5rem', width: '1.5rem', height: '1.5rem' },
      '&-item': {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100%',
        width: '100%',
      },
      '&-hover-navigators &-nav-button': {
        pointerEvents: 'none',
        opacity: 0,
        transition: `opacity ${duration} ease-in-out`,
      },
      '&-hover-navigators &-items-container:hover &-nav-button': {
        pointerEvents: 'all',
        opacity: 1,
      },
      '&-hover-navigators &-items-container:hover &-nav-button-disabled': { pointerEvents: 'none' },
      '&-caption': {
        position: 'absolute',
        bottom: 0,
        left: 0,
        width: '100%',
        background: 'rgba(0,0,0,0.5)',
        color: colorTextLightSolid || '#fff',
        padding: '1rem',
      },
      '&-thumbnails': { display: 'flex', flexDirection: 'column', overflow: 'auto', flexShrink: 0 },
      '&-thumbnail-content': {
        display: 'flex',
        flexDirection: 'row',
        background: colorBgLayout,
        padding: '1rem 0.25rem',
      },
      '&-thumbnail-nav-button': {
        alignSelf: 'center',
        flex: '0 0 auto',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        position: 'relative',
        margin: '0 0.5rem',
        padding: 0,
        border: 'none',
        userSelect: 'none',
        cursor: 'pointer',
        background: 'transparent',
        color: colorTextSecondary,
        width: '2rem',
        height: '2rem',
        transition: `background ${duration},color ${duration},outline-color ${duration}`,
        outlineColor: 'transparent',
        borderRadius: `${borderRadius}px`,
        '&:not(&-disabled):hover': { background: colorBgLayout, color: colorText },
        '&:not(&-disabled):focus-visible': {
          boxShadow: focusShadow,
          outline: '2px solid ' + colorPrimary,
          outlineOffset: '2px',
        },
        '&-disabled': { opacity: 0.6, pointerEvents: 'none' },
      },
      '&-thumbnail-prev-button, &-thumbnail-next-button': {},
      '&-thumbnail-prev-icon, &-thumbnail-next-icon': {
        fontSize: '1rem',
        width: '1rem',
        height: '1rem',
      },
      '&-thumbnails-viewport': { overflow: 'hidden', width: '100%' },
      '&:not(&-thumbnails-right):not(&-thumbnails-left) &-thumbnail-nav-button:dir(rtl)': {
        transform: 'rotate(180deg)',
      },
      '&-thumbnail-items': {
        display: 'flex',
        '&:dir(rtl)': { flexDirection: 'row-reverse' },
        '&-hidden &-thumbnail-item': { visibility: 'hidden' },
        '&-hidden &-thumbnail-item-active': { visibility: 'visible' },
      },
      '&-thumbnail-item': {
        overflow: 'auto',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        opacity: 0.5,
        '&:hover,&-current': { opacity: 1, transition: 'opacity 0.3s' },
        '&-active': { opacity: 1 },
      },
      '&-thumbnail': { outlineColor: 'transparent' },
      '&-thumbnails-left &-content, &-thumbnails-right &-content': { flexDirection: 'row' },
      '&-thumbnails-left &-items-container, &-thumbnails-right &-items-container': {
        flexDirection: 'row',
      },
      '&-thumbnails-left &-items-container, &-thumbnails-top &-items-container': { order: 2 },
      '&-thumbnails-left &-thumbnails, &-thumbnails-top &-thumbnails': { order: 1 },
      '&-thumbnails-left &-thumbnail-content, &-thumbnails-right &-thumbnail-content': {
        flexDirection: 'column',
        flexGrow: 1,
      },
      '&-thumbnails-left &-thumbnail-items, &-thumbnails-right &-thumbnail-items': {
        flexDirection: 'column',
        height: '100%',
      },
      '&-indicator-list': {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '1rem',
        gap: '0.5rem',
        margin: 0,
        listStyle: 'none',
      },
      '&-indicator-button': {
        display: 'inline-flex',
        alignItems: 'center',
        background: colorBorderSecondary,
        width: '1rem',
        height: '1rem',
        transition: `background ${duration},color ${duration},outline-color ${duration},box-shadow ${duration}`,
        outlineColor: 'transparent',
        borderRadius: '50%',
        margin: 0,
        padding: 0,
        border: 'none',
        userSelect: 'none',
        cursor: 'pointer',
        '&:hover': { background: colorTextDisabled },
        '&:focus-visible': {
          boxShadow: focusShadow,
          outline: '2px solid ' + colorPrimary,
          outlineOffset: '2px',
        },
      },
      '&-indicator-active &-indicator-button': { background: colorPrimary },
      '&-indicators-left &-items-container, &-indicators-right &-items-container': {
        flexDirection: 'row',
        alignItems: 'center',
      },
      '&-indicators-left &-items, &-indicators-top &-items': { order: 2 },
      '&-indicators-left &-indicator-list, &-indicators-top &-indicator-list': { order: 1 },
      '&-indicators-left &-indicator-list, &-indicators-right &-indicator-list': {
        flexDirection: 'column',
      },
      '&-inset-indicators &-indicator-list': {
        position: 'absolute',
        display: 'flex',
        zIndex: 1,
        background: 'rgba(0,0,0,0.5)',
      },
      '&-inset-indicators &-indicator-button': { background: 'rgba(255,255,255,0.4)' },
      '&-inset-indicators &-indicator-button:hover': { background: 'rgba(255,255,255,0.6)' },
      '&-inset-indicators &-indicator-active &-indicator-button': {
        background: 'rgba(255,255,255,0.9)',
      },
      '&-inset-indicators&-indicators-top &-indicator-list': {
        top: 0,
        left: 0,
        width: '100%',
        alignItems: 'flex-start',
      },
      '&-inset-indicators&-indicators-right &-indicator-list': {
        right: 0,
        top: 0,
        height: '100%',
        alignItems: 'flex-end',
      },
      '&-inset-indicators&-indicators-bottom &-indicator-list': {
        bottom: 0,
        left: 0,
        width: '100%',
        alignItems: 'flex-end',
      },
      '&-inset-indicators&-indicators-left &-indicator-list': {
        left: 0,
        top: 0,
        height: '100%',
        alignItems: 'flex-start',
      },
      '&-close-button': {
        position: 'absolute',
        top: 0,
        right: 0,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        margin: '0.5rem',
        background: na,
        color: colorTextSecondary,
        width: '3rem',
        height: '3rem',
        padding: 0,
        border: 'none',
        userSelect: 'none',
        cursor: 'pointer',
        borderRadius: '50%',
        outlineColor: 'transparent',
        transition: `background ${duration},color ${duration},outline-color ${duration}`,
        '&:hover': { background: nh, color: colorText },
        '&:focus-visible': {
          boxShadow: focusShadow,
          outline: '2px solid ' + colorPrimary,
          outlineOffset: '2px',
        },
      },
      '&-close-icon': { fontSize: '1.5rem', width: '1.5rem', height: '1.5rem' },
      '&-mask &-nav-button': { position: 'fixed', top: '50%' },
      '&-header': {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '0.5rem',
        background: colorBgLayout,
      },
      '&-footer': {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '0.5rem',
        background: colorBgLayout,
      },
    },
    '.xy-galleria-enter-active': {
      animationName: 'xy-galleria-enter',
      animationDuration: '300ms',
      animationTimingFunction: 'cubic-bezier(0.19,1,0.22,1)',
    },
    '.xy-galleria-leave-active': {
      animationName: 'xy-galleria-leave',
      animationDuration: '300ms',
      animationTimingFunction: 'cubic-bezier(0.19,1,0.22,1)',
    },
  } as CSSObject;
});
