/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Basic: typeof import('./examples/button/basic.vue')['default']
    Block: typeof import('./examples/button/block.vue')['default']
    ButtonGroup: typeof import('./examples/button/button-group.vue')['default']
    Danger: typeof import('./examples/button/danger.vue')['default']
    Demo: typeof import('./.vitepress/vitepress/components/Demo.vue')['default']
    Disabled: typeof import('./examples/button/disabled.vue')['default']
    Ghost: typeof import('./examples/button/ghost.vue')['default']
    Icon: typeof import('./examples/button/icon.vue')['default']
    Loading: typeof import('./examples/button/loading.vue')['default']
    Multiple: typeof import('./examples/button/multiple.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Size: typeof import('./examples/button/size.vue')['default']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/demo/vp-source-code.vue')['default']
  }
}
