import type { CSSObject } from '../../_util/cssinjs';
import { genComponentStyleHook } from '../../theme/internal';

export interface ComponentToken {}

export default genComponentStyleHook('TreeTable', token => {
  const {
    componentCls,
    colorBgLayout,
    colorText,
    colorBorder,
    paddingSM,
    paddingMD,
    paddingLG,
    paddingXS,
    colorBgContainer,
    colorPrimary,
    colorTextSecondary,
  } = token;
  const headerCellPadding = `${paddingSM}px ${paddingMD}px`;
  const bodyCellPadding = `${paddingSM}px ${paddingMD}px`;
  const footerCellPadding = `${paddingSM}px ${paddingMD}px`;
  const cellPaddingSM = `${paddingXS}px ${paddingSM}px`;
  const cellPaddingLG = `${paddingMD}px ${paddingLG}px`;
  const selectedBg = `color-mix(in srgb, ${colorPrimary} 10%, transparent)`;
  const focusRing = `2px solid ${colorPrimary}`;
  const duration = '0.2s';
  return {
    [componentCls]: {
      position: 'relative',
      display: 'block',
      '&-table': { borderSpacing: 0, borderCollapse: 'separate', width: '100%' },
      '&-table-container': { overflow: 'auto' },
      '&-scrollable &-table-container': { position: 'relative' },
      '&-table-scrollable &-head': { insetBlockStart: 0, zIndex: 1 },
      '&-table-scrollable &-body-frozen': { position: 'sticky', zIndex: 1 },
      '&-table-scrollable &-foot': { insetBlockEnd: 0, zIndex: 1 },
      '&-scrollable &-cell-frozen': { position: 'sticky', background: colorBgLayout },
      '&-table-scrollable &-head &-cell-frozen': { zIndex: 1 },
      '&-scrollable &-table-container > &-table > &-head, &-scrollable &-table-container > &-table > &-foot':
        { background: colorBgLayout },
      '&-flex-scrollable': { display: 'flex', flexDirection: 'column', height: '100%' },
      '&-flex-scrollable &-table-container': {
        display: 'flex',
        flexDirection: 'column',
        flex: 1,
        height: '100%',
      },
      '&-table-resizable &-head > tr > th, &-table-resizable &-foot > tr > td, &-table-resizable &-body > tr > td':
        { overflow: 'hidden', whiteSpace: 'nowrap' },
      '&-table-resizable &-head > tr > th&-cell-resizable:not(&-cell-frozen)': {
        backgroundClip: 'padding-box',
        position: 'relative',
      },
      '&-table-resizable-fit &-head > tr > th&-cell-resizable:last-child &-column-resizer': {
        display: 'none',
      },
      '&-column-resizer': {
        display: 'block',
        position: 'absolute',
        insetBlockStart: 0,
        insetInlineEnd: 0,
        margin: 0,
        width: '0.5rem',
        height: '100%',
        padding: 0,
        cursor: 'col-resize',
        border: '1px solid transparent',
      },
      '&-column-header-content': { display: 'flex', alignItems: 'center', gap: `${paddingXS}px` },
      '&-column-resize-indicator': {
        width: '2px',
        position: 'absolute',
        zIndex: 10,
        display: 'none',
        background: colorPrimary,
      },
      '&-mask': {
        position: 'absolute',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
      },
      '&-loading-icon': { fontSize: '2rem', width: '2rem', height: '2rem' },
      '&-pagination-top': {
        borderColor: colorBorder,
        borderStyle: 'solid',
        borderWidth: '0 0 1px 0',
      },
      '&-pagination-bottom': {
        borderColor: colorBorder,
        borderStyle: 'solid',
        borderWidth: '1px 0 0 0',
      },
      '&-header': {
        background: colorBgLayout,
        color: colorText,
        borderColor: colorBorder,
        borderStyle: 'solid',
        borderWidth: '0 0 1px 0',
        padding: `${paddingMD}px`,
      },
      '&-footer': {
        background: colorBgLayout,
        color: colorText,
        borderColor: colorBorder,
        borderStyle: 'solid',
        borderWidth: '0 0 1px 0',
        padding: `${paddingMD}px`,
      },
      '&-cell-header': {
        padding: headerCellPadding,
        background: colorBgLayout,
        borderColor: colorBorder,
        borderStyle: 'solid',
        borderWidth: '0 0 1px 0',
        color: colorText,
        fontWeight: 'normal',
        textAlign: 'start',
        transition: `background ${duration},color ${duration},border-color ${duration},outline-color ${duration},box-shadow ${duration}`,
      },
      '&-column-title': { fontWeight: 600 },
      '&-body > tr': {
        outlineColor: 'transparent',
        background: colorBgContainer,
        color: colorText,
        transition: `background ${duration},color ${duration},border-color ${duration},outline-color ${duration},box-shadow ${duration}`,
      },
      '&-body > tr > td': {
        textAlign: 'start',
        borderColor: colorBorder,
        borderStyle: 'solid',
        borderWidth: '0 0 1px 0',
        padding: bodyCellPadding,
      },
      '&-hoverable &-body > tr:not(&-row-selected):hover': {
        background: colorBgLayout,
        color: colorText,
      },
      '&-body > tr&-row-selected': { background: selectedBg, color: colorPrimary },
      '&-body > tr&-row-selected + tr&-row-selected > td, &-body > tr:has(+ &-row-selected) > td': {
        borderBlockEndColor: colorPrimary,
      },
      '&-body > tr:focus-visible, &-body > tr&-row-contextmenu-selected': {
        boxShadow: 'none',
        outline: focusRing,
        outlineOffset: -1,
      },
      '&-foot > tr > td': {
        textAlign: 'start',
        padding: footerCellPadding,
        borderColor: colorBorder,
        borderStyle: 'solid',
        borderWidth: '0 0 1px 0',
        color: colorText,
        background: colorBgLayout,
      },
      '&-column-footer': { fontWeight: 600 },
      '&-cell-sortable': { cursor: 'pointer', userSelect: 'none', outlineColor: 'transparent' },
      '&-column-title, &-sort-icon, &-sort-badge': { verticalAlign: 'middle' },
      '&-sort-icon': {
        color: colorTextSecondary,
        fontSize: '0.875rem',
        width: '0.875rem',
        height: '0.875rem',
        transition: `color ${duration}`,
      },
      '&-cell-sortable:not(&-cell-sorted):hover': { background: colorBgLayout, color: colorText },
      '&-cell-sortable:not(&-cell-sorted):hover &-sort-icon': { color: colorPrimary },
      '&-cell-sorted': { background: selectedBg, color: colorPrimary },
      '&-cell-sorted &-sort-icon': { color: colorPrimary },
      '&-cell-sortable:focus-visible': { boxShadow: 'none', outline: focusRing, outlineOffset: -1 },
      '&-hoverable &-row-selectable': { cursor: 'pointer' },
      '&-gridlines &-header': { borderWidth: '1px 1px 0 1px' },
      '&-gridlines &-footer': { borderWidth: '0 1px 1px 1px' },
      '&-gridlines &-pagination-top': { borderWidth: '1px 1px 0 1px' },
      '&-gridlines &-pagination-bottom': { borderWidth: '0 1px 1px 1px' },
      '&-gridlines &-head > tr > th': { borderWidth: '1px 0 1px 1px' },
      '&-gridlines &-head > tr > th:last-child': { borderWidth: 1 },
      '&-gridlines &-body > tr > td': { borderWidth: '1px 0 0 1px' },
      '&-gridlines &-body > tr > td:last-child': { borderWidth: '1px 1px 0 1px' },
      '&-gridlines &-body > tr:last-child > td': { borderWidth: '1px 0 1px 1px' },
      '&-gridlines &-body > tr:last-child > td:last-child': { borderWidth: 1 },
      '&-gridlines &-foot > tr > td': { borderWidth: '1px 0 1px 1px' },
      '&-gridlines &-foot > tr > td:last-child': { borderWidth: '1px 1px 1px 1px' },
      '&-gridlines &-head + &-foot > tr > td': { borderWidth: '0 0 1px 1px' },
      '&-gridlines &-head + &-foot > tr > td:last-child': { borderWidth: '0 1px 1px 1px' },
      '&-gridlines:has(&-head):has(&-body) &-body > tr > td': { borderWidth: '0 0 1px 1px' },
      '&-gridlines:has(&-head):has(&-body) &-body > tr > td:last-child': {
        borderWidth: '0 1px 1px 1px',
      },
      '&-gridlines:has(&-body):has(&-foot) &-body > tr:last-child > td': {
        borderWidth: '0 0 0 1px',
      },
      '&-gridlines:has(&-body):has(&-foot) &-body > tr:last-child > td:last-child': {
        borderWidth: '0 1px 0 1px',
      },
      '&-sm &-header': { padding: headerCellPadding },
      '&-sm &-head > tr > th': { padding: cellPaddingSM },
      '&-sm &-body > tr > td': { padding: cellPaddingSM },
      '&-sm &-foot > tr > td': { padding: cellPaddingSM },
      '&-sm &-footer': { padding: headerCellPadding },
      '&-lg &-header': { padding: cellPaddingLG },
      '&-lg &-head > tr > th': { padding: cellPaddingLG },
      '&-lg &-body > tr > td': { padding: cellPaddingLG },
      '&-lg &-foot > tr > td': { padding: cellPaddingLG },
      '&-lg &-footer': { padding: cellPaddingLG },
      '&-body-cell-content': { display: 'flex', alignItems: 'center', gap: `${paddingXS}px` },
      '&-row-selected &-node-toggle-button': { color: 'inherit' },
      '&-node-toggle-button': {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        position: 'relative',
        width: '1.75rem',
        height: '1.75rem',
        color: colorTextSecondary,
        border: '0 none',
        background: 'transparent',
        cursor: 'pointer',
        borderRadius: '50%',
        transition: `background ${duration},color ${duration},border-color ${duration},outline-color ${duration},box-shadow ${duration}`,
        outlineColor: 'transparent',
        userSelect: 'none',
      },
      '&-node-toggle-button:enabled:hover': { color: colorText, background: colorBgLayout },
      '&-row-selected &-node-toggle-button:hover': {
        background: colorBgContainer,
        color: colorPrimary,
      },
      '&-node-toggle-button:focus-visible': {
        boxShadow: 'none',
        outline: focusRing,
        outlineOffset: -1,
      },
      '&-node-toggle-icon:dir(rtl)': { transform: 'rotate(180deg)' },
    },
  } as CSSObject;
});
