// Vite plugin: 拦截 `vue` 模块解析，返回带类型 stub 的虚拟模块。
//
// 解决源码里 `import { Ref } from 'vue'` 这种没写 `import type` 但 Ref 是
// TypeScript interface 的情况。vue runtime bundle 不导出 Ref，
// 会在 SSR 时报 "does not provide an export named 'Ref'"。
//
// 同时 SSR 编译产物里 SFC 可能会 import vue 的 runtime helper
// （如 resolveComponent / defineComponent 等）。这些必须真正从 vue 来。
//
// 关键：stub 内部的 `export * from "vue"` 不能被自己拦截，否则会循环引用。
// resolveId 根据 importer 判断：只有从外部 import 'vue' 时才走 stub，
// 从 stub 内部 import 'vue' 时返回 null，让 rollup 用默认解析器找真实 vue。

const TYPE_STUB_NAMES = Array.from(new Set([
  'Ref',
  'CSSProperties',
  'VNode',
  'VNodeChild',
  'VNodeChildAtom',
  'VNodeArrayChildren',
  'VNodeProps',
  'PropType',
  'Component',
  'MaybeRef',
  'MaybeRefOrGetter',
  'ObjectEmitsOptions',
  'EmitsOptions',
  'SetupContext',
  'Slot',
  'Slots',
  'SlotsType',
  'DefineComponent',
  'AsyncComponentLoader',
  'RenderFunction',
  'DirectiveBinding',
  'DirectiveArgument',
  'DirectiveModifiers',
  'DirectiveHook',
  'DirectiveModifiersObject',
  'PropOptions',
  'ExtractPropTypes',
  'ExtractPublicPropTypes',
  'ComponentOptions',
  'ComponentOptionsMixin',
  'ComponentOptionsWithoutProps',
  'ComponentOptionsWithArrayProps',
  'ComponentOptionsWithObjectProps',
  'ComponentCustomOptions',
  'ComponentCustomProperties',
  'ComponentPublicInstance',
  'ConcreteComponent',
  'FunctionalComponent',
  'FunctionComponent',
  'ComputedRef',
  'WatchSource',
  'WatchStopHandle',
  'WatchCallback',
  'WatchEffect',
  'WatchHandle',
  'InjectionKey',
  'WritableComputedRef',
  'ToRefs',
  'ShallowRef',
  'ToRef',
  'UnwrapRef',
  'ShallowUnwrapRef',
  'StyleValue',
  'Plugin',
  'PluginObject',
  'Directive',
  'App',
  'AppContext',
  'HTMLAttributes',
  'AriaAttributes',
  'SVGAttributes',
  'ReservedProps',
  'TransitionProps',
  'TransitionGroupProps',
  'TransitionState',
]))

// 我们的策略：把 vue 的所有 ESM 导出 pass through (export *)，
// 再显式声明 TS interface 类型为 undefined stub。
// Rollup 静态分析时能看到所有 export（包括 type stubs）；
// 运行时这些 type stubs 是 undefined（接口本就不存在运行时），
// runtime helpers 是真实的 vue 函数。
const VIRTUAL_ID = '\0xiaoye-ui-vue-stubs'

export default function vueTypeStubPlugin() {
  return {
    name: 'xiaoye-ui-vue-type-stubs',
    enforce: 'pre',

    resolveId(id, importer) {
      // 拦截 'vue' 解析为虚拟 stub。但 stub 内部的 `export * from "vue"`
      // 必须解析为真实的 vue，否则会出现循环引用。
      if (id === 'vue') {
        if (importer === VIRTUAL_ID) {
          return null // 让 vite/rollup 用默认解析器找真正的 vue
        }
        return VIRTUAL_ID
      }
      return null
    },

    load(id) {
      if (id === VIRTUAL_ID) {
        const stubLines = TYPE_STUB_NAMES.map(
          (n) => `export const ${n} = undefined`,
        ).join('\n')

        const code = [
          '// Auto-generated by xiaoye-ui-vue-type-stubs plugin',
          'export * from "vue"',
          stubLines,
          '',
        ].join('\n')

        return code
      }
      return null
    },
  }
}
