/* eslint-disable no-console */
/**
 * prebuild 脚本
 * 自动生成 components.ts、typings/global.d.ts、package.json exports
 * 消除手工维护的漂移风险
 *
 * 生成物：
 * 1. src/components.ts     - 组件聚合入口（从 src/ 扫描）
 * 2. typings/global.d.ts   - Vue GlobalComponents 类型声明
 * 3. package.json exports  - 每个组件的双入口（./<name> + ./<name>/style）
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync, mkdirSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');
const srcDir = resolve(pkgRoot, 'src');
const typingsDir = resolve(pkgRoot, 'typings');

// 非组件目录，不扫描
const EXCLUDE_DIRS = [
  '_util',
  '_shared',
  'style',
  'theme',
  'locale',
  'version',
  'components',
  'config',
];

// 不作为对外导出的组件目录（内部实现）
const HIDDEN_DIRS = ['vc-'];

// 不生成 export * 的组件目录：这些模块与其他模块存在同名命名导出（类型）冲突
const EXPORT_STAR_EXCEPTIONS = [
  'cascader',
  'list',
  'select',
  'message',
  'notification',
  // 以下目录存在跨模块命名导出冲突，仅保留 default 导出
  'radio', // 导出 Button 与 button 冲突
  'menu', // 导出 Divider 与 divider 冲突
  'date-picker', // 导出 TimePicker 与 time-picker 冲突
  'icon', // 无命名导出
  'col', // 实际来自 grid，与 grid 冲突
  'row', // 实际来自 grid，与 grid 冲突
];

// 替代 export * 的显式命名导出语句（key 为组件目录名）
const NAMED_EXPORT_OVERRIDES = {
  message: "export { message } from './message';",
  notification: "export { notification } from './notification';",
};

/**
 * 判断目录是否为组件目录
 */
function isComponentDir(name) {
  if (name.startsWith('_') || name.startsWith('.')) return false;
  if (EXCLUDE_DIRS.includes(name)) return false;
  if (HIDDEN_DIRS.some(prefix => name.startsWith(prefix))) return false;
  return statSync(join(srcDir, name)).isDirectory();
}

/**
 * 扫描组件目录，获取所有组件名
 */
function scanComponents() {
  const components = [];
  const dirs = readdirSync(srcDir).filter(isComponentDir);

  for (const dir of dirs) {
    // 主入口
    for (const entry of ['index.ts', 'index.tsx']) {
      const entryPath = join(srcDir, dir, entry);
      if (existsSync(entryPath)) {
        components.push({ name: dir, entry: entryPath, hasStyle: false });
        break;
      }
    }

    // style 入口
    const lastIdx = components.length - 1;
    if (lastIdx >= 0) {
      for (const entry of ['index.ts', 'index.tsx']) {
        const stylePath = join(srcDir, dir, 'style', entry);
        if (existsSync(stylePath)) {
          components[lastIdx].hasStyle = true;
          break;
        }
      }
    }
  }

  return components;
}

/**
 * 转为 PascalCase
 */
function toPascalCase(name) {
  // 处理 kebab-case: input-number -> InputNumber
  return name
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * 生成 components.ts
 * 策略：为每个组件目录生成 export * 聚合 + default 导出 + style 副作用导入
 * 使用 export * 自动透传所有命名导出（组件、子组件、类型、props 等）
 */
function generateComponentsTs(components) {
  const lines = [
    '// Auto-Generated by prebuild.mjs - DO NOT EDIT',
    '// prettier-ignore',
    '/* eslint-disable import/export */',
    '',
  ];

  for (const comp of components) {
    const pascalName = toPascalCase(comp.name);
    // 聚合所有命名导出（含类型）；黑名单中的模块因存在跨模块同名导出冲突，跳过 export *
    if (EXPORT_STAR_EXCEPTIONS.includes(comp.name)) {
      if (NAMED_EXPORT_OVERRIDES[comp.name]) {
        lines.push(NAMED_EXPORT_OVERRIDES[comp.name]);
      }
    } else {
      lines.push(`export * from './${comp.name}';`);
    }
    // default 导出转为命名导出
    lines.push(`export { default as ${pascalName} } from './${comp.name}';`);
    if (comp.hasStyle) {
      lines.push(`import './${comp.name}/style';`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * 生成 typings/global.d.ts
 * 为每个组件生成 XY<ComponentName> 声明
 */
function generateGlobalDts(components) {
  const lines = [
    '/* eslint-disable @typescript-eslint/consistent-type-imports */',
    '// Auto-Generated by prebuild.mjs - DO NOT EDIT',
    "declare module 'vue' {",
    '  export interface GlobalComponents {',
  ];

  for (const comp of components) {
    const pascalName = toPascalCase(comp.name);
    const xyName = `XY${pascalName}`;
    lines.push(`    ${xyName}: (typeof import('xiaoye-ui'))['${pascalName}'];`);
  }

  lines.push('  }', '}', 'export {};');
  return lines.join('\n') + '\n';
}

/**
 * 生成 package.json 的 exports 字段（开发期指向 src）
 */
function generateExports(components) {
  const exports = {
    '.': './src/index.ts',
    './package.json': './package.json',
  };

  for (const comp of components) {
    // 主入口
    for (const ext of ['.ts', '.tsx']) {
      const entryPath = `src/${comp.name}/index${ext}`;
      if (existsSync(resolve(pkgRoot, entryPath))) {
        exports[`./${comp.name}`] = `./${entryPath}`;
        break;
      }
    }

    // style 入口
    if (comp.hasStyle) {
      for (const ext of ['.ts', '.tsx']) {
        const stylePath = `src/${comp.name}/style/index${ext}`;
        if (existsSync(resolve(pkgRoot, stylePath))) {
          exports[`./${comp.name}/style`] = `./${stylePath}`;
          break;
        }
      }
    }
  }

  return exports;
}

/**
 * 更新 package.json 的 exports 字段
 */
function updatePackageJsonExports(exports) {
  const pkgPath = resolve(pkgRoot, 'package.json');
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
  pkg.exports = exports;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8');
}

// === 主流程 ===
console.log('[prebuild] 开始扫描组件...');

const components = scanComponents();
console.log(`[prebuild] 扫描到 ${components.length} 个组件`);

// 1. 生成 components.ts
const componentsTs = generateComponentsTs(components);
const componentsTsPath = resolve(srcDir, 'components.ts');
writeFileSync(componentsTsPath, componentsTs, 'utf-8');
console.log(`[prebuild] 已生成 ${componentsTsPath}`);

// 2. 生成 typings/global.d.ts
if (!existsSync(typingsDir)) {
  mkdirSync(typingsDir, { recursive: true });
}
const globalDts = generateGlobalDts(components);
const globalDtsPath = resolve(typingsDir, 'global.d.ts');
writeFileSync(globalDtsPath, globalDts, 'utf-8');
console.log(`[prebuild] 已生成 ${globalDtsPath}`);

// 3. 更新 package.json exports
const exports = generateExports(components);
updatePackageJsonExports(exports);
console.log(`[prebuild] 已更新 package.json exports（${Object.keys(exports).length} 个入口）`);

console.log('[prebuild] 完成');
